POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "nom": "aladin",
  "email": "aladin@test.com",
  "password": "123456"
}

###

# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "aladin@test.com",
  "password": "123456"
}

###
### ============================
### TESTS COURS
### ============================

### Récupérer tous les cours
GET http://localhost:3000/cours

###

### Récupérer un cours par son id
GET http://localhost:3000/cours/1


###
### ============================
### TESTS LEÇONS
### ============================

### Récupérer toutes les leçons
GET http://localhost:3000/lecons

###

### Récupérer une leçon par son id
GET http://localhost:3000/lecons/1

###

### Récupérer toutes les leçons d'un cours
GET http://localhost:3000/lecons/cours/1
####






//tous les quizs
GET http://localhost:3000/api/quiz

### 

//afficher un quiz
GET http://localhost:3000/api/quiz/5

###

// importer un quiz
POST http://localhost:3000/api/quiz/importer
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "titre": "Test3"
}

###

// Modifier un quiz
PUT http://localhost:3000/api/quiz/6
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "titre": "Quiz mis à jour",
  "score": 10
}

###

DELETE http://localhost:3000/api/quiz/8
Authorization: Bearer {{login.response.body.token}}

####

//associer un quiz a un lecon
PATCH http://localhost:3000/api/quiz/5/lier-lecon
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "leconId": 2
}






###

# @name inscrire
POST http://localhost:3000/inscriptions
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "coursId": 1
}

###

GET http://localhost:3000/inscriptions/moi
Authorization: Bearer {{login.response.body.token}}3

